* Practicalities

** Learning goals

The learning goals of this course are:

1. Ability to understand and critically evaluate current research papers in (pragmatic) NLG.
2. Ability to reproduce (simpler) simulations from the literature.
3. Confidence in critically assessing the methodology and manner of reporting in research papers.

For more on reproducibility in CL, see [[http://dx.doi.org/10.1162/coli_a_00330][Wieling et al. (2018)]].

** Course requirements

The course is not intended as a first introduction to programming, Python, or neural networks.
It is recommended that you bring the following:

- prior experience in programming in Python
  + prior knowledge of PyTorch is not required
- some prior knowledge in statistical modeling, maybe even neural networks
 + linear algebra, probability calculus, (simple) linear regression modeling

** Credits & Grading

The course is worth 6 credit points.

There are two things necessary for course completion:

1. homework exercises
2. final course project

The final grade is calculated as 0.4 * homework grade + 0.6 * project grade.

*** Homework exercises

There will be (ususally: weekly) homework exercises.
Everybody must hand these in individually.
*Cooperation is discouraged at this point.*
You need to have at least a passing grade to be allowed to take part in the final course projects.

*** Final course projects

You will be working in a small group on a final course project.
The modal project is a replication and critical assessment of a research paper.
A list of topic suggestions will be made available.

** Time & venue

Time: Wednesdays 9:00-12:00

First meeting: October 26 2022

Venue: Wilhelmstraße 19, room 0.01

Some lectures will be delivered online, via Zoom, in this [[https://zoom.us/my/michael.franke.tuebingen][zoom room]].

In order to submit your homework and receive information for this course (by emaiil), please sign up for this course on [[https://moodle.zdv.uni-tuebingen.de/course/view.php?id=2875][Moodle]].

** References

Wieling, M., Rawee, J., & van Noord, G. (2018). Reproducibility in computational linguistics: are we willing to share? Computational Linguistics, 44(4), 641–649. http://dx.doi.org/10.1162/coli_a_00330
